# Generated by Django 5.2.6 on 2025-09-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('acceso_bloqueado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_mascota', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('pez', 'Pez'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('raza', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'mascota',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('bloque', models.CharField(max_length=10)),
                ('piso', models.IntegerField()),
                ('numero', models.CharField(max_length=10)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(default='activa', max_length=20)),
                ('tipo_unidad', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('local', 'Local Comercial'), ('oficina', 'Oficina'), ('deposito', 'Depósito'), ('parqueadero', 'Parqueadero'), ('otro', 'Otro')], default='apartamento', help_text='Tipo de unidad', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'unidad',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('acceso_bloqueado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('tag_codigo', models.CharField(help_text='Código unico del tag de acceso', max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado')], default='activo', max_length=20)),
                ('tipo_vehiculo', models.CharField(choices=[('automovil', 'Automóvil'), ('motocicleta', 'Motocicleta'), ('camioneta', 'Camioneta'), ('bicicleta', 'Bicicleta'), ('otro', 'Otro')], default='automovil', max_length=20)),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
    ]
