# Generated by Django 5.2.6 on 2025-09-12 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idRol',
            field=models.ForeignKey(blank=True, db_column='idrol', null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.rol'),
        ),
    ]
