# Generated by Django 5.2.6 on 2025-09-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='idRol',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='rol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='rol',
            table=None,
        ),
    ]
