# Generated by Django 5.2.6 on 2025-09-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_idrol'),
        ('users', '0003_remove_rol_id_rol_created_at_rol_idrol_and_more'),
    ]

    operations = [
    ]
