# Generated by Django 5.2.6 on 2025-09-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250912_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personamodel',
            name='documento',
        ),
        migrations.AddField(
            model_name='personamodel',
            name='ci',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personamodel',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
