# Generated by Django 5.2.6 on 2025-09-12 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=100, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('requiere_pago', models.BooleanField(default=False)),
                ('precio_por_bloque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('apertura_hora', models.TimeField()),
                ('cierre_hora', models.TimeField()),
                ('dias_habiles', models.CharField(max_length=50)),
                ('reglas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('ocupado', 'Ocupado'), ('libre', 'Libre')], default='activo', max_length=10)),
            ],
            options={
                'db_table': 'area_comun',
            },
        ),
        migrations.CreateModel(
            name='AutorizacionVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('motivo_visita', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'autorizacion_visita',
            },
        ),
        migrations.CreateModel(
            name='RegistroVisitaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registro_visita',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('url_comprobante', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('nota', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
