# Generated by Django 5.2.6 on 2025-09-11 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_comun', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionvisita',
            name='copropietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.copropietariomodel'),
        ),
        migrations.AddField(
            model_name='autorizacionvisita',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.personamodel'),
        ),
        migrations.AddField(
            model_name='registrovisitamodel',
            name='autorizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_comun.autorizacionvisita'),
        ),
        migrations.AddField(
            model_name='registrovisitamodel',
            name='guardia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.guardiamodel'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='area_comun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='area_comun.areacomun'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='users.copropietariomodel'),
        ),
    ]
