# Generated by Django 5.2.6 on 2025-09-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_comun', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionvisita',
            name='motivo_visita',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
