# Generated by Django 5.2.6 on 2025-09-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='url_imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
