# Generated by Django 5.2.6 on 2025-09-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='url_imagen',
            new_name='imagen_url',
        ),
    ]
