# Generated by Django 5.2.6 on 2025-09-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0003_rename_url_imagen_comunicado_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
