# Generated by Django 5.2.6 on 2025-09-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0003_comunicado_url_imagen'),
        ('comunicacion', '0004_alter_comunicado_fecha_publicacion_and_more'),
    ]

    operations = [
    ]
