# Generated by Django 5.2.6 on 2025-09-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0005_merge_20250912_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='url_imagen',
        ),
    ]
